import type { Project } from "@/types/project";

/* project card */
export const projects: Project[] = [
  {
    id: "karhutla",
    ariaLabel: "Buka detail Karhutla",
    tabLabel: "Machine Learning",
    titleLines: ["Karhutla Detection"],
    meta: "GEMASTIK XIX 2026",
    tags: ["Astro", "NASA FIRMS API", "Python", "JavaScript"],
    refYear: "2026",
    img: "/gmi/karhutla.webp",
    imgAlt: "Karhutla - EWS",
    modalTitleLines: ["Karhutla Detection - EWS"],
    desc: "Website Early Warning System (EWS) untuk mendeteksi potensi kebakaran hutan dan lahan (karhutla) di Indonesia. Menggunakan data satelit NASA FIRMS API untuk memantau titik panas secara real-time, dengan visualisasi peta interaktif dan notifikasi peringatan dini.",
    metaValue: "Machine Learning · Dashboard",
    chips: [{ color: "#0048ff", label: "NASA FIRMS API" },{ color: "#ff5d01", label: "Astro" }, { color: "#2f77db", label: "Python" }, { color: "#e2bf21", label: "JavaScript" }],
    actionHref: "https://www.karhutla.site",
    actionTarget: "_blank",
    actionLabel: "Lihat Proyek",
  },
  {
    id: "bstp",
    ariaLabel: "Buka detail BSTP",
    tabLabel: "Client Project",
    titleLines: ["Company Profile & Katalog Produk"],
    meta: "PT. Bintang Surya Teknik Persada",
    tags: ["Astro", "Tailwind CSS", "JavaScript"],
    refYear: "2026",
    img: "/gmi/bstp.webp",
    imgAlt: "BSTP - PT. Bintang Surya Teknik Persada",
    modalTitleLines: ["PT. Bintang Surya Teknik Persada"],
    desc: "Website company profile & katalog produk untuk PT. Bintang Surya Teknik Persada, distributor mechanical-electrical resmi untuk elektromotor, gearbox, pompa industri, inverter, dan kompresor angin. Dibangun sebagai proyek klien dengan Astro dan pendekatan hybrid CSS + Tailwind, mencakup etalase produk dengan filter kategori, halaman profil perusahaan, integrasi company profile PDF, serta akses kontak langsung ke tim sales lewat WhatsApp.",
    metaValue: "Client Project · Company Website",
    chips: [{ color: "#ff5d01", label: "Astro" }, { color: "#38bdf8", label: "Tailwind CSS" }, { color: "#e2bf21", label: "JavaScript" }],
    actionHref: "https://www.ptbintangsuryateknikpersada.com",
    actionTarget: "_blank",
    actionLabel: "Lihat Proyek",
  },
  {
    id: "strukin",
    ariaLabel: "Buka detail StruckIn",
    tabLabel: "AI",
    titleLines: ["StrukIn"],
    meta: "AI Project",
    tags: ["Python", "JSX", "API"],
    refYear: "2025",
    img: "/gmi/strukin.webp",
    imgAlt: "StrukIn - Aplikasi Struktur Data",
    modalTitleLines: ["StrukIn"],
    desc: "Dhika dan saya membuat aplikasi berbasis AI yang menggabungkan backend Python dengan antarmuka frontend berbasis JSX (React), terintegrasi dengan API untuk mendukung pemrosesan data secara otomatis. Deskripsi ini masih perlu disesuaikan lebih lanjut sesuai detail sebenarnya dari proyek kami berdua.",
    metaValue: "AI Project",
    chips: [{ color: "#3572a5", label: "Python" }, { color: "#61dafb", label: "JSX" }, { color: "#6e40c9", label: "API" }],
    actionHref: "https://struk-in-app.vercel.app",
    actionTarget: "_blank",
    actionLabel: "Lihat Proyek",
  },
  {
    id: "sekolah",
    ariaLabel: "Buka detail sekolah",
    tabLabel: "Landing Page",
    titleLines: ["Website Sekolah"],
    meta: "Website",
    tags: ["HTML", "CSS", "JavaScript"],
    refYear: "2025",
    img: "/gmi/sman-6-depok.webp",
    imgAlt: "SMAN 6 Depok - Website Sekolah",
    modalTitleLines: ["Website Sekolah"],
    desc: "Landing page untuk program Campus Goes to School",
    metaValue: "Website",
    chips: [{ color: "#f7751e", label: "HTML" }, { color: "#3572a5", label: "CSS" }, { color: "#e2bf21", label: "JavaScript" }],
    actionHref: "https://ejerai.github.io/Campus-Goes-To-School",
    actionTarget: "_blank",
    actionLabel: "Lihat Proyek",
  },
  {
    id: "futclub",
    ariaLabel: "FutClub",
    tabLabel: "Android",
    titleLines: ["FutClub"],
    meta: "Android Studio",
    tags: ["Java", "Kotlin", "Firebase", "PHP Rest API", "MySQL"],
    refYear: "2026",
    img: "/gmi/futclub.webp",
    imgAlt: "FutClub",
    modalTitleLines: ["FutClub"],
    desc: "Aplikasi Android untuk komunitas semua olahraga, dibangun dengan Android Studio dan backend PHP REST API terhubung ke MySQL. Dilengkapi antarmuka bergaya glassmorphism, alur login dengan Google, serta integrasi Firebase untuk mendukung fitur-fitur real-time di dalam aplikasi.",
    metaValue: "Aplikasi Mobile",
    chips: [{ color: "#c8922a", label: "Java" }, { color: "#7f52ff", label: "Kotlin" }, { color: "#ffca28", label: "Firebase" }, { color: "#8892be", label: "PHP Rest API" }, { color: "#e29c41", label: "MySQL" }],
    actionHref: "https://github.com/ejerai/FutClub",
    actionTarget: "_blank",
    actionLabel: "Lihat Proyek",
  },
  {
    id: "bansos",
    ariaLabel: "Buka detail Bansos",
    tabLabel: "ML/Dashboard",
    titleLines: ["Bansos Crawl Data", "X/Twitter"],
    meta: "Machine Learning & Dashboard",
    tags: ["Python", "Google Colab", "Streamlit"],
    refYear: "2026",
    img: "/gmi/machine-learning.webp",
    imgAlt: "Machine Learning & Dashboard",
    modalTitleLines: ["Bansos Crawl Data", "X/Twitter"],
    desc: "Proyek tugas akhir (UAS) yang menganalisis diskursus masyarakat Indonesia terkait program bantuan sosial (bansos) di platform X/Twitter. Mencakup clustering K-Means, analisis sentimen dengan InSet Lexicon, social network analysis, hingga dashboard interaktif berbasis Streamlit untuk memvisualisasikan hasil analisis.",
    metaValue: "Machine Learning & Dashboard",
    chips: [{ color: "#3572a5", label: "Python" }, { color: "#f37626", label: "Jupyter Notebook" }, { color: "#f9ab00", label: "Google Colab" }, { color: "#ff4b4b", label: "Streamlit" }],
    actionHref: "https://github.com/ejerai/project-uas-atms",
    actionTarget: "_blank",
    actionLabel: "Lihat Proyek",
  },
  {
    id: "laundry",
    ariaLabel: "Buka detail Laundry Dashboard",
    tabLabel: "Dashboard",
    titleLines: ["Laundry Management", "Admin & Customer"],
    meta: "Alle Laundry",
    tags: ["HTML", "CSS", "PHP", "MySQL", "Midtrans"],
    refYear: "2026",
    img: "/gmi/laundry.webp",
    imgAlt: "Tampilan website Preloved Kampus Universitas Budi Luhur",
    modalTitleLines: ["Laundry Management", "Admin & Customer"],
    desc: "Sistem manajemen laundry berbasis web dengan panel admin dan panel pelanggan yang terpisah. Mendukung pemesanan layanan, pelacakan status cucian, serta integrasi pembayaran online melalui Midtrans untuk mempermudah transaksi antara pelanggan dan pihak laundry.",
    metaValue: "Alle Laundry · Aplikasi Web",
    chips: [{ color: "#f7751e", label: "HTML" }, { color: "#3572a5", label: "CSS" }, { color: "#8892be", label: "PHP" }, { color: "#e29c41", label: "MySQL" }, { color: "#0099e5", label: "Midtrans" }],
    actionHref: "http://alle-laundry.gt.tc",
    actionTarget: "_blank",
    actionLabel: "Lihat Proyek",
  },
  {
    id: "sentiment",
    ariaLabel: "Buka detail Analisis Sentimen Media Sosial",
    tabLabel: "E-Commerce",
    titleLines: ["Preloved Kampus", "Universitas Budi Luhur"],
    meta: "Blogger · Website Redesign",
    tags: ["HTML", "CSS", "JavaScript"],
    refYear: "2025",
    img: "/gmi/UBL-Preloved-Ezra-Rahmaditya.webp",
    imgAlt: "Tampilan website Preloved Kampus Universitas Budi Luhur",
    modalTitleLines: ["Preloved Kampus", "Universitas Budi Luhur"],
    desc: "Mempermudah Mahasiswa Universitas Budi Luhur dalam mencari dan menawar barang bekas secara efisien dan aman. dan pasti nya memberikan peluang untuk Mahasiswa yang mau menjual barang bekas mereka.",
    metaValue: "Blogger Website Redesign",
    chips: [{ color: "#f7751e", label: "HTML" }, { color: "#3572a5", label: "CSS" }, { color: "#e2bf21", label: "JavaScript" }],
    actionHref: "https://www.ublpreloved.web.id",
    actionTarget: "_blank",
    actionLabel: "Lihat Proyek",
  },
];
